### ISSUE TITLE
Tests are failing, but RPM build is not

### ISSUE THREAD

**Issue by hroncok** [fedora-python/python3#2] opened 2015-01-30 13:35 UTC
```
4 tests failed:
    test_ensurepip test_site test_ssl test_venv
21 tests skipped:
    test_curses test_devpoll test_ioctl test_kqueue test_msilib
    test_ossaudiodev test_pep277 test_smtpnet test_socketserver
    test_startfile test_systemtap test_timeout test_tk
    test_ttk_guionly test_unicode_file test_urllib2net test_urllibnet
    test_winreg test_winsound test_xmlrpc_net test_zipfile64
```

This is form latest build. However, the RPM builds. This should have failed.

**Comment by rkuska** [comment] 2015-01-30 17:22
```
1439 CheckPython() {                                                                                     
1440   ConfName=$1                                                                                       
1441   ConfDir=$(pwd)/build/$ConfName                                                                    
1442                                                                                                     
1443   echo STARTING: CHECKING OF PYTHON FOR CONFIGURATION: $ConfName                                    
1444                                                                                                     
1445   # Note that we're running the tests using the version of the code in the                          
1446   # builddir, not in the buildroot.                                                                 
1447                                                                                                     
1448   # Run the upstream test suite, setting "WITHIN_PYTHON_RPM_BUILD" so that the                      
1449   # our non-standard decorators take effect on the relevant tests:                                  
1450   #   @unittest._skipInRpmBuild(reason)                                                             
1451   #   @unittest._expectedFailureInRpmBuild                                                          
1452   # test_faulthandler.test_register_chain currently fails on ppc64le and                            
1453   #   aarch64, see upstream bug http://bugs.python.org/issue21131                                   
1454   WITHIN_PYTHON_RPM_BUILD= \                                                                        
1455   LD_LIBRARY_PATH=$ConfDir $ConfDir/python -m test.regrtest \                                       
1456     --verbose --findleaks \                                                                         
1457     %ifarch ppc64le aarch64                                                                         
1458     -x test_faulthandler \                                                                          
1459     %endif                                                                                          
1460     %ifarch %{power64} s390 s390x                                                                   
1461     -x test_gdb                                                                                     
1462     %endif                                                                                          
1463                                                                                                     
1464   echo FINISHED: CHECKING OF PYTHON FOR CONFIGURATION: $ConfName                                    
1465                                                                                                     
1466 }     
```

The problem is probably the `echo` function at the bottom, this makes the return code of CheckPython function 0 (but it should not reach it and fail immediately after tests).
Maybe this could help (?):

```
....
rcode=$?
echo FINISHED: CHECKING OF PYTHON FOR CONFIGURATION: $ConfName  
return $rcode

}
```

Even though I don't understand why sometimes the build stops right after the tests finish with failure.

**Comment by hroncok** [comment] 2015-01-30 17:37
Thanks, I'll try that.

> Even though I don't understand why sometimes the build stops right after the tests finish with failure.

That's weird, maybe some quantum madness is happening :)

**Comment by sYnfo** [comment] 2015-01-30 17:43
I don't think what @rkuska wrote is the issue. The %check section is run with 'set -e', meaning it should fail whenever _any_ command returns nonzero return value (with some exceptions [0]). Therefore if 'python -m test.regrtest' correctly returns nonzero value and 'set -e' is in effect, the final echo should be a non-issue.

[0] http://linux.die.net/man/1/bash
-e
Exit immediately if a pipeline (which may consist of a single simple command), a subshell command enclosed in parentheses, or one of the commands executed as part of a command list enclosed by braces (see SHELL GRAMMAR above) exits with a non-zero status. The shell does not exit if the command that fails is part of the command list immediately following a while or until keyword, part of the test following the if or elif reserved words, part of any command executed in a && or ││ list except the command following the final && or ││, any command in a pipeline but the last, or if the command's return value is being inverted with !. A trap on ERR, if set, is executed before the shell exits. This option applies to the shell environment and each subshell environment separately (see COMMAND EXECUTION ENVIRONMENT above), and may cause subshells to exit before executing all the commands in the subshell.

**Comment by sYnfo** [comment] 2015-01-30 17:55
Take for instance this simple check section. It fails even though the last command in the function returns 0.

```
%check
check() {
    false
    true
}

check
```

**Comment by hroncok** [comment] 2015-01-30 17:56
```
[~]$ set -e
[~]$ functiontest() { fooooo; echo OK; }
[~]$ functiontest
```

This also exists the shell, so what @sYnfo says is quite true.

**Comment by sYnfo** [comment] 2015-01-30 18:04
@hroncok could you try to rebuild it with `echo $?` directly after the `python -m test.regrtest` line, so that we can see what it's returning? If it is 0 then the problem is prolly in regrtest, otherwise it could be rpmbuild/bash.

**Comment by hroncok** [comment] 2015-01-30 18:19
Building. https://copr.fedoraproject.org/coprs/churchyard/python3-nightly/build/69891/

Shouldn't take more than one hour ;)

**Comment by hroncok** [comment] 2015-01-30 19:13
```
$ grep 'EXIT CODE OF TEST SUITE' build.log 
EXIT CODE OF TEST SUITE: 1
EXIT CODE OF TEST SUITE: 1
```

**Comment by sYnfo** [comment] 2015-01-30 20:10
Fails correctly in Koji [0], perhaps a copr bug.

[0] http://koji.fedoraproject.org/koji/taskinfo?taskID=8784483

**Comment by rkuska** [comment] 2015-01-30 20:41
I have witnessed these false builds on koji and brew also (can't find a link tho).

Couldn't it be some sort of enviroment differencies between build machines rather than services?

**Comment by rkuska** [comment] 2015-01-30 20:53
> Bash experts seem to agree: “never rely on set -e” (gnu.bash.bug, BashFAQ). The recommendation is to do your own error checking by stringing together a series of commands with “&&” like this

http://david.rothlis.net/shell-set-e/

Bash experts seem to agree with my proposed fix :-D

**Comment by rkuska** [comment] 2015-01-30 21:06
@hroncok Can you try the build with my proposed fix? To see if the set -e will ignore also the return code of the function inside %check. There is a jar of peanut butter at stake.

**Comment by hroncok** [comment] 2015-01-31 06:57
Pushed. Will wait for night build to test it.

BTW You can all push stuff as well, the cron job will pull it. Just be sure to not push --force anything.

**Comment by rkuska** [comment] 2015-02-01 22:21
So I have tried to reproduce this behaviour.
1. New copr, it worked as expected and build failed.
2. Mock, again the same result.

So this led me to think that the cause might be the environment and I went for `scl enable` and boy, was I right.

Once again mock with `scl-utils-build` and `python35-build` in buildroot and build passed the check phase.

I have put `echo CHECK FOR SET -E SETTINGS IN ENABLE: $-` inside `scl enable` where we call our `CheckPython` function.

This is the output of `echo` call:
 `CHECK FOR SET -E SETTINGS IN ENABLE: hB`

As you can see the `e` is missing. 

Also:

```
+ echo CHECK FOR SET -E SETTINGS OUT OF ENABLE: ehxB                                                
CHECK FOR SET -E SETTINGS OUT OF ENABLE: ehxB 
```

My proposed fix works but only if the later call of `CheckPython optimized` is unsuccessful because even if the `CheckPython debug` returns `1` `CheckPython optimized` is still executed. 

So if we go with my fix every call of `CheckPython` should be enclosed in its own `scl enable` or instead we could try call `set -e` inside the `scl enable`.

**Comment by rkuska** [comment] 2015-02-02 08:08
I've just found that this was already discussed in scl upstream and closed as NOTABUG.

https://bugzilla.redhat.com/show_bug.cgi?id=1184515

**Comment by hroncok** [comment] 2015-02-02 09:33
Thanks. The build are now not working for some other weird reason anyway :(

**Closed as completed** 2016-02-16 17:41 UTC
Labels: bug
